---
- name: Update package cache
  ansible.builtin.apt:
    update_cache: true
    upgrade: dist
    cache_valid_time: 3600
  become: true

- name: Install Apache, MySQL and PHP
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
  loop:
    - "{{ lamp_apache_name }}"
    - mysql-server
    - php
    - php-mysql
  notify: Restart apache

- name: Ensure Apache is running and enabled on Debian
  ansible.builtin.service:
    name: apache2
    state: started
    enabled: true
