---
- name: Install Apache, MySQL and PHP
  ansible.builtin.yum:
    name: "{{ item }}"
    state: present
  loop:
    - httpd
    - mysql-server
    - php
    - php-mysql
  notify: Restart apache

- name: Ensure Apache is running and enabled on Red Hat
  ansible.builtin.service:
    name: httpd
    state: started
    enabled: true
