---
- name: Install pip, NGINX, MySQL and PHP
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
  loop:
    - "{{ lemp_nginx_name }}"
    - python3-pip
    - mysql-server
    - php
    - php-mysqlnd
    - php-fpm
    - php-opcache
    - php-gd
    - php-xml
    - php-json
  notify: Restart nginx

- name: Ensure php-fpm is running and enabled on Red Hat
  ansible.builtin.service:
    name: php-fpm
    state: started
    enabled: true

- name: Sets Nginx conf file
  ansible.builtin.template:
    src: "{{ role_path }}/templates/nginx.conf.j2"
    dest: "/etc/nginx/conf.d/{{ http_conf }}"
    mode: "0644"

- name: Removes "default" site
  ansible.builtin.file:
    path: "/etc/nginx/conf.d/default"
    state: absent
  notify: Reload nginx

- name: Install PyMySQL
  ansible.builtin.pip:
    name: pymysql
    state: present

- name: Ensure mysqld is running and enabled on Red Hat
  ansible.builtin.service:
    name: mysqld
    state: started
    enabled: true

- name: Create MySQL root user with password
  community.mysql.mysql_user:
    name: root
    password: "{{ lemp_mysql_password }}"
    login_user: root
    login_password: ''

- name: Removes all anonymous user accounts
  community.mysql.mysql_user:
    name: ''
    host_all: true
    login_user: root
    login_password: "{{ lemp_mysql_password }}"
    state: absent

- name: Remove test database
  community.mysql.mysql_db:
    name: test
    state: absent
    login_user: root
    login_password: "{{ lemp_mysql_password }}"

- name: Sets Up PHP Info Page
  ansible.builtin.template:
    src: "{{ role_path }}/templates/info.php.j2"
    dest: "/var/www/html/info.php"
    mode: "0644"

- name: Ensure NGINX is running and enabled on Red Hat
  ansible.builtin.service:
    name: "{{ lemp_nginx_name }}"
    state: started
    enabled: true
