---
- name: Install NGINX, MySQL and PHP
  ansible.builtin.yum:
    name: "{{ item }}"
    state: present
  loop:
    - "{{ lemp_nginx_name }}"
    - mysql-server
    - php
    - php-mysql
  notify: Restart nginx

- name: Ensure NGINX is running and enabled on Red Hat
  ansible.builtin.service:
    name: "{{ lemp_nginx_name }}"
    state: started
    enabled: true
